# ko build configuration
# See: https://ko.build/configuration/

# Use distroless as the base image for smaller, secure containers
defaultBaseImage: gcr.io/distroless/static:nonroot

# Build settings
builds:
  - id: terraform-action
    dir: ./cmd/terraform-action
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
