projects:
  - name: production
    dir: examples/terraform
    autoplan:
      enabled: true
      when_modified: ["*.tf", "*.tfvars", ".terraform.lock.hcl"]
    plan_requirements: []
    apply_requirements: []

tfcmt:
  enabled: true
  skip_no_changes: true
  ignore_warning: false
