name: 'Terraform PR Action'
description: 'Run Terraform plan/apply based on PR comments, similar to Atlantis, using tfcmt'
author: 'tkasuz'

branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  github-token:
    required: true
    description: GitHub token for PR comments and checks
  config-path:
    description: 'Path to .terraform-action.yaml configuration file'
    required: false
    default: '.terraform-action.yaml'

runs:
  using: 'node20'
  main: 'dist/index.js'
